name: Deploy PDF Reader Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t pdf-reader-app .

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push bimberman/pdf-reader-app:latest

      - name: Deploy to EC2
        needs: build
        runs-on: self-hosted
        steps:
          - name: Pull Docker image
            run: docker pull bimberman/pdf-reader-app:latest

          - name: Stop and remove existing container
            run: docker stop pdf-reader-app-container || true && docker rm pdf-reader-app-container || true

          - name: Run Docker container
            run: docker run -d -p 3000:3000 -name pdf-reader-app-container  bimberman/pdf-reader-app
