import type { Metadata } from "next";
import { GeistMono } from "geist/font";
import { GeistSans } from "geist/font";
import "./globals.css";

const geistMono = GeistMono;
const geistSans = GeistSans;

export const metadata: Metadata = {
  title: "PDF Reader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/pdf.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
